from __future__ import annotations

import json
from pathlib import Path


STARTER_TASK = {
    "schema_version": 1,
    "task_id": "hello-reprojudge",
    "domain": "starter",
    "paper": "synthetic:hello-reprojudge",
    "title": "Hello ReproJudge",
    "instructions": "Produce metrics.json with status=ok. The evaluator owns the checks.",
    "expected_artifacts": ["metrics.json"],
    "checks": [
        {
            "type": "json_equals",
            "artifact": "metrics.json",
            "json_path": "status",
            "expected": "ok",
        }
    ],
    "timeout_seconds": 30,
}

STARTER_AGENT = '''from __future__ import annotations

import json
import os
from pathlib import Path

output = Path(os.environ["REPROJUDGE_OUTPUT_DIR"])
telemetry = Path(os.environ["REPROJUDGE_TELEMETRY_PATH"])
output.mkdir(parents=True, exist_ok=True)

(output / "metrics.json").write_text(
    json.dumps({"status": "ok"}, sort_keys=True) + "\\n",
    encoding="utf-8",
)
telemetry.write_text(
    json.dumps(
        {
            "agent_name": "hello-reprojudge-agent",
            "agent_version": "1",
            "provider": "deterministic-local",
            "token_usage": 0,
            "model_cost_usd": 0.0,
            "interventions": [],
        },
        sort_keys=True,
    )
    + "\\n",
    encoding="utf-8",
)
'''

STARTER_README = '''# ReproJudge starter

This directory was generated by `reprojudge init`.

Run the deterministic starter:

```bash
reprojudge validate tasks/hello-reprojudge.json
reprojudge run tasks/hello-reprojudge.json --output runs -- python3 agent.py
reprojudge summarize runs
```

Then replace `agent.py` with your agent command and edit the task contract. Evaluator `checks` stay evaluator-side; the generated agent-visible request does not include them.

Useful next steps:

- task contract: https://github.com/XiantingWu/ReproJudge/blob/main/docs/TASK_SPEC.md
- benchmark authoring: https://github.com/XiantingWu/ReproJudge/blob/main/docs/AUTHORING.md
- agent integration: https://github.com/XiantingWu/ReproJudge/blob/main/docs/INTEGRATING_AGENTS.md
- trust model: https://github.com/XiantingWu/ReproJudge/blob/main/docs/TRUST_MODEL.md
'''


def create_starter(directory: Path) -> list[Path]:
    root = Path(directory)
    if root.is_symlink():
        raise ValueError("starter directory must not be a symlink")
    if root.exists():
        if not root.is_dir():
            raise ValueError("starter path must be a directory")
        if any(root.iterdir()):
            raise ValueError("starter directory must be empty; refusing to overwrite existing files")
    else:
        root.mkdir(parents=True, exist_ok=False)

    tasks = root / "tasks"
    tasks.mkdir()
    task_path = tasks / "hello-reprojudge.json"
    agent_path = root / "agent.py"
    readme_path = root / "README.md"

    task_path.write_text(
        json.dumps(STARTER_TASK, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    agent_path.write_text(STARTER_AGENT, encoding="utf-8")
    readme_path.write_text(STARTER_README, encoding="utf-8")
    return [task_path, agent_path, readme_path]
